eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
microservice:
  PAYEMENT-SERVICE:
    endpoints:
      endpoint:
        uri: http://PAYMENT-SERVICE/payment/doPayment
  ORDER-SERVICE:
    endpoints:
      endpoint:
        uri: http://ORDER-SERVICE/order/bookOrder
